services:
  - type: web
    name: new-test
    runtime: docker
    repo: https://github.com/wroxtaaar/new-test
    branch: main
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: SEEDR_API_TOKEN
        sync: false
      - key: SEEDR_SESSION_SECRET
        sync: false
      - key: ALLOW_LEGACY_SEEDR_TOKEN
        sync: false
